name: Weekly Python Script Run

on:
  push:
  schedule:
    - cron: '0 0 * * 0'

env:
  TZ: Asia/Shanghai
  
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
          python -m pip install pyyaml

      - name: Run
        run: |
          python ./rulesets/sukka/convert.py
          python ./rulesets/custom_list/merge.py

      - name: Commit
        env:
          GIT_NAME: ${{ secrets.GIT_NAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        run: |
          git config --local user.name $GIT_NAME
          git config --local user.email $GIT_EMAIL
          git add .
          git commit -m "Github action update at `date '+%Y-%m-%d %H:%M:%S'`."
     
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: main 
